### ISSUE TITLE
英語での報告の仕方が分からない: 表現について

### ISSUE THREAD

**Issue by hiroyuki-sato** [oss-gate/first-feedback-guidebook#10]
国語は苦手ですが、以下のようにすると読みやすいように感じました。(あくまで私の感想です。)

https://github.com/oss-gate/first-feedback-guidebook/blob/master/chapters/english.md

* おおむね似たようなことが書かれていました。 -> 似たようなことが書かれていました。
* だいたい似たような感じの -> 似たような感じの
* 「だいたい通じる下手な英語」で大抵は間に合います 。 -> 「だいたい通じる下手な英語」で間に合います 。
* 「相手に隙があれば目ざとくそれを突いて、とにかく自分の利益を最大化しよう、という考え方をしている相手」-> 「相手に隙があれば目ざとくそれを突いて、とにかく自分の利益を最大化しようとする相手」

**Comment by piroor** [comment]
ご指摘ありがとうございます。自分はどうも持って回った言い方をよくしてしまうようで……
ご提案いただいた内容でも十分そうだったのですが、それぞれ、より誤解が少なくなりそうな感じで改めてみました。

**Comment by hiroyuki-sato** [comment]
ありがとうございます！
