### ISSUE TITLE
文章が途中で終わっている

### ISSUE THREAD

**Issue by hiroyuki-sato** [oss-gate/first-feedback-guidebook#11]
文章が途中でおわっています。

https://github.com/oss-gate/first-feedback-guidebook/blob/master/chapters/support.md#技術情報の間違いを見つけたらフィードバックのチャンス

> 「英語版ではこう書いてあるのに、日本語

**Comment by piroor** [comment]
ありがとうございます！ 見落としていました。

**Comment by hiroyuki-sato** [comment]
ありがとうございます！
