### ISSUE TITLE
プロプライエタリ& エスカレーション

### ISSUE THREAD

**Issue by hiroyuki-sato** [oss-gate/first-feedback-guidebook#12]
以下言葉は別の言葉に置き換えても良いように感じました。
(意味を知らない人もいるんじゃないかという懸念です)

* [プロプライエタリ](https://github.com/oss-gate/first-feedback-guidebook/blob/master/chapters/motivation.md#僕たちは根本的な解決を図りたい)
* [エスカレーション](https://github.com/oss-gate/first-feedback-guidebook/blob/master/chapters/hesitation.md#場違いな報告していいんです)

**Comment by piroor** [comment]
ご指摘ありがとうございます！ 「プロプライエタリ」については説明無しで使ってしまっていたので、最初に登場する箇所で注釈を加えました。
エスカレーションについては、報告先をどこにするかの話の中で説明しているので大丈夫と思います。

**Comment by hiroyuki-sato** [comment]
ありがとうございます！
