### ISSUE TITLE
「Is this intentional?（これは意図的なことですか？）」?

### ISSUE THREAD

**Issue by hiroyuki-sato** [oss-gate/first-feedback-guidebook#18]
https://github.com/oss-gate/first-feedback-guidebook/blob/master/chapters/english.md

「これ」の説明があった方が良い気がしますがどうでしょう？

例えば以下のような

> この実際に得られた結果は意図的なものか確認する意味で「Is this intentional?」とでも添えればOKです。

**Comment by piroor** [comment]
反応しそびれていました、すみません。
簡単に、訳の方だけ「この結果は意図的なものですか？」に訂正することにしました！
