### ISSUE TITLE
電子書籍用データ・印刷用データのビルド手順を実施しても最終成果物ができない

### ISSUE THREAD

**Issue by array** [oss-gate/first-feedback-guidebook#20]
README.mdの電子書籍用データ・印刷用データのビルド手順を実施したが書籍ができなかった。

再現手順
README.mdの通りに実施。

途中でくわえたこと

1. Rubyのgemが無かった
- **対応**
- aptでgemをインストール
でインストール（エラーメッセージがこれだった）

2. gemでインストールしようとしたら 
- ` /var/lib/gems.2.5.0`
のPermissionが無かった

- **対応**
- `$ sudo chmod 777 /var/lib/gems/2.5.0`
を実施

3. ruby.hが無かった
- **対応**
- aptでrubt~devをインストール

4. makeが無かった
- **対応**
- aptでbuild-essential をインストール。

5. npmが無かった
-**対応**
-aptでnpmをインストール

6. npm install -g . でエラー
- `/usr/local/lib /usr/local/bin のPermissionを777に変更

その後全部終了したが最後のMakeで
`make: *** No targets specified and no makefile found.  Stop.`
でできなかった。
実際 ~にはMakfileが無かった。

期待される結果
makeで書籍が作成される。

**Comment by piroor** [comment]
手動でのchmodは非推奨です。
手順を見直したところ、`gem install unicode-display_width`と`npm install -g .`の前に`sudo`が抜けていました。すみません。
これらのコマンドは管理者権限で実行することが想定されます。

npmのインストールですが、aptで入る物は古いので、 https://qiita.com/bigplants/items/2d75bf552e0da4a7e822 で紹介されているような手順で最新安定版のnpmを使える状態にしたほうがいいかもしれません。
（この事が原因でインストールに失敗する場合がありそうです。）
こちらでは、gemとnpmのバージョンは以下の通りでした。

```sh
$ gem --version
2.7.6
$ npm --version
6.4.1
```

また、肝心のこのリポジトリをcloneする手順が抜けていました。
（このリポジトリをcloneしたところから始まる想定だったので、敢えては書いていませんでした。）

以上を踏まえ、READMEに記載の手順を訂正しました。
https://github.com/oss-gate/first-feedback-guidebook/blob/master/README.md#%E9%9B%BB%E5%AD%90%E6%9B%B8%E7%B1%8D%E7%94%A8%E3%83%87%E3%83%BC%E3%82%BF%E5%8D%B0%E5%88%B7%E7%94%A8%E3%83%87%E3%83%BC%E3%82%BF%E3%81%AE%E3%83%93%E3%83%AB%E3%83%89%E6%89%8B%E9%A0%86
こちらでもう1度試して頂けますでしょうか？

ただ、今回の手順で本来パーミッションを777にする必要がない箇所を777にしてしまっているため、これが原因で手順に失敗するようになってしまっている恐れはあります。
万全を期すのであれば、これらの変更を元に戻す（といっても、どこがどう変わったか今となっては確認のしようもないため、実際にはシステムの再インストールということになってしまいそうです……）ことをお薦めします。

なお、途中で何度かエラーが出たと書かれていますが、このようなケースについては
「どのコマンドの実行時にエラーが出たのか」
「実際に端末に出力されたエラーメッセージはどのようなものだったか」
をそのまま貼り付けて頂けると幸いです。
（こちらで推測して「こうだろう」と補った内容が、実際の状況と違っていると二度手間になるので、そのようにすることをお勧めしています。）

**Comment by array** [comment]
やり直してみました。
一旦、WSLのUbuntuをアンインストールして再インストール。
`sudo apt update`
`sudo apt upgrade`
で最新化しました。

以下のところで若干手順を変えました。

- npmの最新化
提示していただいたQiitaの文書がMac用だったのでとりあえず
`sudo apt nodejs`
をしたあと、
`npm install -g n`
を実行しようとしたら、npmが無いというエラーになりました。
そこで、Ubuntuでnpmの最新化はどうするかを検索したところ、
[Qiita Ubuntuに最新のNode.jsを難なくインストールする](https://qiita.com/seibe/items/36cef7df85fe2cefa3ea)
を参照してNode.jsとnpmの最新化を行いました。
この結果
`~$ npm --version`
6.13.4
となりました。

- bundleのエラー
`$ bundle install --path vendor/bundle`
でエラー
`Command 'bundle' not found, but can be installed with:`
`sudo apt install ruby-bundler`
がでたのでそのままapt installを実施しました。

結果、無事にファイル
first-feedback-guidebook-ebook.pdf
first-feedback-guidebook-print.pdf
first-feedback-guidebook.epub
を作成することができました。

**Comment by piroor** [comment]
ああ、bundlerも抜けてましたね……手順に加えておきます！（筆者環境ではgemで入れてました）

**Comment by piroor** [comment]
まっさらな環境からの手順の記述については改善されたということで、closeしても大丈夫でしょうか？

**Comment by array** [comment]
はい、ありがとうございます。何か達成感があります。

**Comment by piroor** [comment]
また何かありましたらフィードバック頂けると幸いです！
