### ISSUE TITLE
辞書にない語: 役者不足

### ISSUE THREAD

**Issue by ayatronics** [oss-gate/first-feedback-guidebook#25]
よく間違われて使われる表現ですが、「役者不足」は「力不足」の誤用と思われます。
検索していただければ、詳細が書かれた記事が確認できますので、ご参照ください。

記載がある場所は、「プルリクエストしてみたい！」の「本来するべきだったこと」項です。
https://github.com/oss-gate/first-feedback-guidebook/blob/0d11ecba30966a19e5e392fa7dcd425db9a9639a/chapters/pullrequest.md#%E6%9C%AC%E6%9D%A5%E3%81%99%E3%82%8B%E3%81%B9%E3%81%8D%E3%81%A0%E3%81%A3%E3%81%9F%E3%81%93%E3%81%A8

**Comment by piroor** [comment]
ご指摘ありがとうございます。
「こういう文脈での"役不足"は誤用だ」という話の中で見かけて「そういう言葉があるのか」と思って使っていましたが、少なくとも伝統的な辞書には載っていない造語だったんですね。

ただ、「力不足」には「頑張ったんだけど力が及ばなかった」みたいなニュアンスを自分は感じるのですが、この事例は「こんな事くらい俺ならできる、と驕っていたが実は全然実力が足りていなかった」という文脈なので、よりその文脈に適した語を使いたいなという思いがあります。
自分の語彙では、以下が近い所にある気がしています。

* 分不相応
* 器じゃない
* 身の程を知らない・わきまえない（直後の文章ではこちらの表現を使っています）

ということで、「器じゃない」を使って f1f6b5aafe850cbd72d5fc1b6b8a44a4b5d5e0b5 と書き換えてみました。

**Comment by ayatronics** [comment]
ありがとうございます！
細かい指摘で申し訳ありません……。

**Comment by piroor** [comment]
エアリプの形になってしまっていました、すみません。動揺して過剰反応したという部分もあると思っています。
今の時代の日本語としてよりユニバーサルな方に寄せた方が良いという事については全く異論はないので、この変更も妥当だと思っております。
（ちなみに、他の場所でも「これは実力不足と書き換えた方がよい」と指摘を受けました）
