### ISSUE TITLE
本当に「誰でもできる」の？: *「自分がそこに関われる」

### ISSUE THREAD

**Issue by hiroyuki-sato** [oss-gate/first-feedback-guidebook#6]
タグが間違えているようで以下のようになっています。

https://github.com/oss-gate/first-feedback-guidebook/blob/master/chapters/motivation.md

```
*「自分がそこに関われる」とは思えない・思っていないから*
```

**Comment by piroor** [comment]
ご指摘ありがとうございます。これはCMarksの仕様で、鉤括弧等を囲う形の強調はなぜか強調になってくれないんです。。。
いちいちそこを考慮するのも面倒だったので、とりあえずガッと書いた後、最後にまとめて直そうと思っていたのでした。

**Comment by hiroyuki-sato** [comment]
なるほど、そうでしたか。もうCloseしても大丈夫ですが、同じIssueを立てる人向けにOpenのままがよかったりしますか？

**Comment by piroor** [comment]
この個別の問題については、本文を少し書き直した結果解消されたので、クローズにしようと思います。
もし他にもこういう状態になっている箇所に気付かれましたら、お手数ですがご指摘もしくはプルリクエストをいただければ幸いです！
