### ISSUE TITLE
どう報告すればいいのか分からない: 誤字

### ISSUE THREAD

**Issue by hiroyuki-sato** [oss-gate/first-feedback-guidebook#7]
なりあｍす。 -> なります。
https://github.com/oss-gate/first-feedback-guidebook/blob/master/chapters/how.md

> 開発者コミュニティの目的は、ソフトウェアの改善・改良、ソフトウェアの問題を解決することです。よって、報告する内容もそれに沿ったものとなりあｍす。では、一体どんな情報があれば問題解決の役に立つのでしょうか？

**Comment by piroor** [comment]
ご指摘ありがとうございます、訂正しました！

なお、単純な誤字については「編集」からプルリクエストを直接出して頂いて大丈夫です。（と、校正作業を人任せにしようとする奴）
